/* ============================================================
   model.js — Parametric design model + project persistence
   The single source of truth. Every drawing, render, overlay,
   and concern finding is generated from this structured model.
   ============================================================ */
(function (global) {
  'use strict';

  const STORE_KEY = 'poolbid.projects.v1';
  const ACTIVE_KEY = 'poolbid.active.v1';

  // --- Default new project shape ---
  function defaultProject(overrides) {
    const id = U.uid('prj');
    const now = new Date().toISOString();
    const proj = {
      id,
      client: '',
      address: '',
      apn: '',
      estimator: '',
      notes: '',
      poolType: 'gunite',
      createdAt: now,
      updatedAt: now,
      revisions: [],
      currentRevision: null,

      // Parametric design model (single source of truth)
      model: {
        // lot/site
        site: {
          lotWidthFt: 80,
          lotDepthFt: 110,
          houseWidthFt: 50,
          houseDepthFt: 35,
          housePosition: { xFt: 15, yFt: 8 }, // from lot top-left
        },
        // pool shell
        pool: {
          shape: 'rectangle',
          lengthFt: 30,
          widthFt: 15,
          shallowDepthFt: 3.5,
          deepDepthFt: 6,
          positionFt: { x: 20, y: 55 }, // pool top-left within lot
          rotationDeg: 0,
          features: {
            spa: false,
            steps: true,
            bench: false,
            shelf: false,
            waterFeature: false,
          },
        },
        deck: {
          material: 'concrete',
          avgWidthFt: 4,
        },
        equipment: {
          xFt: 5,
          yFt: 90,
          widthFt: 8,
          depthFt: 5,
        },
        safety: {
          features: [], // selected approved means under CA SPSA
        },
        setbacks: {
          propertyLineFt: 5,
          houseFt: 10,
        },
        // confidence values & provenance for AI-extracted items
        provenance: {},
      },

      // Sketch interpretation results (input artifacts)
      sketch: {
        imageDataUrl: null,
        rotationDeg: 0,
        interpretedAt: null,
        elements: [], // [{type, confidence, status, label}]
      },

      // Geospatial context
      geo: {
        lat: null,
        lng: null,
        accuracy: null,
        imagerySource: null,
        imageryDate: null,
        poolOverlay: null, // {lat, lng, rotationDeg, scale}
      },

      // Concerns (re-generated by rules engine; persisted with revisions)
      concerns: [],
      concernDispositions: {}, // findingId -> 'open' | 'acknowledged' | 'dismissed' | 'resolved' | 'n/a'

      // Export tracking
      exports: [], // [{revisionId, timestamp, kind}]
    };
    return Object.assign(proj, overrides || {});
  }

  // --- Storage layer ---
  function loadAll() {
    return U.store.get(STORE_KEY, {});
  }
  function saveAll(map) {
    return U.store.set(STORE_KEY, map);
  }
  function getActiveId() {
    return U.store.get(ACTIVE_KEY, null);
  }
  function setActiveId(id) {
    if (id) U.store.set(ACTIVE_KEY, id);
    else U.store.remove(ACTIVE_KEY);
  }

  // --- Model API ---
  const Model = {
    list() {
      const m = loadAll();
      return Object.values(m).sort((a, b) => (b.updatedAt || '').localeCompare(a.updatedAt || ''));
    },
    get(id) {
      const m = loadAll();
      return m[id] || null;
    },
    create(initial) {
      const p = defaultProject(initial);
      const m = loadAll();
      m[p.id] = p;
      saveAll(m);
      setActiveId(p.id);
      return p;
    },
    update(id, patch) {
      const m = loadAll();
      if (!m[id]) return null;
      const merged = deepMerge(m[id], patch);
      merged.updatedAt = new Date().toISOString();
      m[id] = merged;
      saveAll(m);
      return merged;
    },
    save(project) {
      const m = loadAll();
      project.updatedAt = new Date().toISOString();
      m[project.id] = project;
      saveAll(m);
      return project;
    },
    duplicate(id) {
      const p = this.get(id);
      if (!p) return null;
      const copy = JSON.parse(JSON.stringify(p));
      copy.id = U.uid('prj');
      copy.client = (p.client || '') + ' (copy)';
      copy.revisions = [];
      copy.currentRevision = null;
      copy.exports = [];
      copy.createdAt = new Date().toISOString();
      copy.updatedAt = copy.createdAt;
      const m = loadAll();
      m[copy.id] = copy;
      saveAll(m);
      return copy;
    },
    remove(id) {
      const m = loadAll();
      delete m[id];
      saveAll(m);
      if (getActiveId() === id) setActiveId(null);
    },
    active() {
      const id = getActiveId();
      return id ? this.get(id) : null;
    },
    setActive(id) {
      setActiveId(id);
    },
    commitRevision(id, note) {
      const p = this.get(id);
      if (!p) return null;
      const revision = {
        id: U.revId(),
        timestamp: new Date().toISOString(),
        note: note || '',
        modelSnapshot: JSON.parse(JSON.stringify(p.model)),
        sketchSnapshot: JSON.parse(JSON.stringify(p.sketch)),
        geoSnapshot: JSON.parse(JSON.stringify(p.geo)),
        concerns: JSON.parse(JSON.stringify(p.concerns || [])),
        modelVersion: '1.0',
        rulesVersion: '1.0',
      };
      p.revisions.push(revision);
      p.currentRevision = revision.id;
      return this.save(p);
    },
    recordExport(id, kind, sheetList) {
      const p = this.get(id);
      if (!p) return null;
      p.exports.push({
        kind,
        sheets: sheetList || [],
        revisionId: p.currentRevision || null,
        timestamp: new Date().toISOString(),
      });
      return this.save(p);
    },
  };

  // --- deep merge (objects only; arrays replaced) ---
  function deepMerge(target, source) {
    if (Array.isArray(source)) return source.slice();
    if (source && typeof source === 'object') {
      const out = Object.assign({}, target);
      for (const k in source) {
        out[k] = k in target ? deepMerge(target[k], source[k]) : source[k];
      }
      return out;
    }
    return source !== undefined ? source : target;
  }

  // --- Sample project for demo flows ---
  Model.sample = function () {
    return defaultProject({
      client: 'Daniel Gaona',
      address: '1234 Easy Lane, Galt, CA 95632',
      apn: '044-313-014',
      estimator: 'Rich Summers',
      poolType: 'gunite',
      notes: 'Installation of 16 x 30, 16,000 gallon in-ground pool with concrete decking. Existing house, septic system; verify locations.',
      model: {
        site: { lotWidthFt: 95, lotDepthFt: 130, houseWidthFt: 55, houseDepthFt: 38, housePosition: { xFt: 18, yFt: 10 } },
        pool: {
          shape: 'rectangle',
          lengthFt: 30, widthFt: 16,
          shallowDepthFt: 3.5, deepDepthFt: 6,
          positionFt: { x: 22, y: 70 }, rotationDeg: 0,
          features: { spa: true, steps: true, bench: true, shelf: true, waterFeature: false },
        },
        deck: { material: 'concrete', avgWidthFt: 6 },
        equipment: { xFt: 6, yFt: 100, widthFt: 9, depthFt: 6 },
        safety: { features: ['fence', 'self-closing-doors'] },
        setbacks: { propertyLineFt: 5, houseFt: 10 },
        provenance: {},
      },
      geo: {
        lat: 38.249,
        lng: -121.298,
        accuracy: 'approximate',
        imagerySource: 'OpenStreetMap (sample)',
        imageryDate: '2025',
        poolOverlay: null,
      },
    });
  };

  global.Model = Model;
})(window);
